export const data = {
      "stocks": [
        {
          "Rank": 1,
          "Company": "Edwards Lifesciences",
          "Ticker": "EW",
          "Industry": "Medical Products",
          "ESG Rating": "AA",
          "Composite Rating": 99,
          "Relative Strength": 96,
          "EPS Rating": 92,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 25,
          "ROE": 32,
          "Last Qtr Sales % Chg": 15,
          "Last Qtr EPS % Chg": 11,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 2,
          "Company": "Equinix",
          "Ticker": "EQIX",
          "Industry": "Finance-Property REIT",
          "ESG Rating": "AA",
          "Composite Rating": 99,
          "Relative Strength": 95,
          "EPS Rating": 94,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": 79,
          "ROE": 5,
          "Last Qtr Sales % Chg": 10,
          "Last Qtr EPS % Chg": 99,
          "Dividend Yield": 1.72
        },
        {
          "Rank": 3,
          "Company": "Prologis",
          "Ticker": "PLD",
          "Industry": "Finance-Property REIT",
          "ESG Rating": "AA",
          "Composite Rating": 99,
          "Relative Strength": 94,
          "EPS Rating": 85,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 12,
          "ROE": 8,
          "Last Qtr Sales % Chg": 38,
          "Last Qtr EPS % Chg": 18,
          "Dividend Yield": 2.38
        },
        {
          "Rank": 4,
          "Company": "Emcor Group",
          "Ticker": "EME",
          "Industry": "Building-Maintenance & Services",
          "ESG Rating": "AA",
          "Composite Rating": 99,
          "Relative Strength": 87,
          "EPS Rating": 96,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 24,
          "ROE": 16,
          "Last Qtr Sales % Chg": 19,
          "Last Qtr EPS % Chg": 21,
          "Dividend Yield": 0.37
        },
        {
          "Rank": 5,
          "Company": "Cadence Design Systems",
          "Ticker": "CDNS",
          "Industry": "Computer Software-Design",
          "ESG Rating": "AA",
          "Composite Rating": 98,
          "Relative Strength": 92,
          "EPS Rating": 97,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 23,
          "ROE": 46,
          "Last Qtr Sales % Chg": 12,
          "Last Qtr EPS % Chg": 27,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 6,
          "Company": "National Research",
          "Ticker": "NRC",
          "Industry": "Commercial Services-Health Care",
          "ESG Rating": "AA",
          "Composite Rating": 97,
          "Relative Strength": 95,
          "EPS Rating": 90,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 39,
          "ROE": 55,
          "Last Qtr Sales % Chg": 12,
          "Last Qtr EPS % Chg": 4,
          "Dividend Yield": 1.32
        },
        {
          "Rank": 7,
          "Company": "NextEra Energy",
          "Ticker": "NEE",
          "Industry": "Utility-Electric Power",
          "ESG Rating": "AAA",
          "Composite Rating": 96,
          "Relative Strength": 92,
          "EPS Rating": 86,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 11,
          "ROE": 11,
          "Last Qtr Sales % Chg": 22,
          "Last Qtr EPS % Chg": 13,
          "Dividend Yield": 2.2
        },
        {
          "Rank": 8,
          "Company": "Microsoft",
          "Ticker": "MSFT",
          "Industry": "Computer Software-Desktop",
          "ESG Rating": "AAA",
          "Composite Rating": 96,
          "Relative Strength": 90,
          "EPS Rating": 94,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 17,
          "ROE": 39,
          "Last Qtr Sales % Chg": 12,
          "Last Qtr EPS % Chg": 21,
          "Dividend Yield": 1.44
        },
        {
          "Rank": 9,
          "Company": "Hasbro",
          "Ticker": "HAS",
          "Industry": "Leisure-Toys/Games/Hobby",
          "ESG Rating": "AA",
          "Composite Rating": 95,
          "Relative Strength": 93,
          "EPS Rating": 93,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": 0,
          "ROE": 27,
          "Last Qtr Sales % Chg": 9,
          "Last Qtr EPS % Chg": 63,
          "Dividend Yield": 2.23
        },
        {
          "Rank": 10,
          "Company": "Owens Corning",
          "Ticker": "OC",
          "Industry": "Building-Construction Products/Misc.",
          "ESG Rating": "AA",
          "Composite Rating": 95,
          "Relative Strength": 91,
          "EPS Rating": 81,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": 13,
          "ROE": 13,
          "Last Qtr Sales % Chg": 5,
          "Last Qtr EPS % Chg": 11,
          "Dividend Yield": 1.4
        },
        {
          "Rank": 11,
          "Company": "Home Depot",
          "Ticker": "HD",
          "Industry": "Retail/Wholesale Building Products",
          "ESG Rating": "AA",
          "Composite Rating": 93,
          "Relative Strength": 90,
          "EPS Rating": 87,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 22,
          "ROE": 0,
          "Last Qtr Sales % Chg": 1,
          "Last Qtr EPS % Chg": 4,
          "Dividend Yield": 2.31
        },
        {
          "Rank": 12,
          "Company": "Herman Miller",
          "Ticker": "MLHR",
          "Industry": "Household/Office Furniture",
          "ESG Rating": "AA",
          "Composite Rating": 93,
          "Relative Strength": 89,
          "EPS Rating": 92,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 13,
          "ROE": 25,
          "Last Qtr Sales % Chg": 7,
          "Last Qtr EPS % Chg": 22,
          "Dividend Yield": 1.87
        },
        {
          "Rank": 13,
          "Company": "Ormat Technologies",
          "Ticker": "ORA",
          "Industry": "Energy-Alternative/Other",
          "ESG Rating": "AA",
          "Composite Rating": 92,
          "Relative Strength": 95,
          "EPS Rating": 85,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": -8,
          "ROE": 6,
          "Last Qtr Sales % Chg": 3,
          "Last Qtr EPS % Chg": 25,
          "Dividend Yield": 0.6
        },
        {
          "Rank": 14,
          "Company": "Texas Instruments",
          "Ticker": "TXN",
          "Industry": "Electronics-Semiconductor Mfg.",
          "ESG Rating": "AA",
          "Composite Rating": 92,
          "Relative Strength": 91,
          "EPS Rating": 81,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 24,
          "ROE": 55,
          "Last Qtr Sales % Chg": -9,
          "Last Qtr EPS % Chg": -1,
          "Dividend Yield": 2.73
        },
        {
          "Rank": 15,
          "Company": "Bright Horizons Family Solutions",
          "Ticker": "BFAM",
          "Industry": "Consumer Services-Education",
          "ESG Rating": "AA",
          "Composite Rating": 92,
          "Relative Strength": 89,
          "EPS Rating": 95,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 20,
          "ROE": 24,
          "Last Qtr Sales % Chg": 8,
          "Last Qtr EPS % Chg": 14,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 16,
          "Company": "Salesforce.com",
          "Ticker": "CRM",
          "Industry": "Computer Software-Enterprise",
          "ESG Rating": "AAA",
          "Composite Rating": 92,
          "Relative Strength": 47,
          "EPS Rating": 91,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 57,
          "ROE": 15,
          "Last Qtr Sales % Chg": 22,
          "Last Qtr EPS % Chg": -7,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 17,
          "Company": "Applied Materials",
          "Ticker": "AMAT",
          "Industry": "Electronics-Semiconductor Equipment",
          "ESG Rating": "AA",
          "Composite Rating": 91,
          "Relative Strength": 96,
          "EPS Rating": 60,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 34,
          "ROE": 54,
          "Last Qtr Sales % Chg": -14,
          "Last Qtr EPS % Chg": -29,
          "Dividend Yield": 1.59
        },
        {
          "Rank": 18,
          "Company": "Keysight Technologies",
          "Ticker": "KEYS",
          "Industry": "Electronics-Scientific/Measuring",
          "ESG Rating": "AA",
          "Composite Rating": 91,
          "Relative Strength": 94,
          "EPS Rating": 89,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 21,
          "ROE": 26,
          "Last Qtr Sales % Chg": 8,
          "Last Qtr EPS % Chg": 40,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 19,
          "Company": "West Pharmaceutical Services",
          "Ticker": "WST",
          "Industry": "Medical Supplies",
          "ESG Rating": "AA",
          "Composite Rating": 91,
          "Relative Strength": 93,
          "EPS Rating": 94,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 14,
          "ROE": 15,
          "Last Qtr Sales % Chg": 5,
          "Last Qtr EPS % Chg": 27,
          "Dividend Yield": 0.45
        },
        {
          "Rank": 20,
          "Company": "Deckers Outdoor",
          "Ticker": "DECK",
          "Industry": "Apparel-Shoes",
          "ESG Rating": "AA",
          "Composite Rating": 90,
          "Relative Strength": 82,
          "EPS Rating": 86,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 38,
          "ROE": 26,
          "Last Qtr Sales % Chg": 10,
          "Last Qtr EPS % Chg": "NA",
          "Dividend Yield": "NA"
        },
        {
          "Rank": 21,
          "Company": "Idexx Laboratories",
          "Ticker": "IDXX",
          "Industry": "Medical Systems/Equipment",
          "ESG Rating": "AA",
          "Composite Rating": 89,
          "Relative Strength": 91,
          "EPS Rating": 94,
          "SMR Rating": "NA",
          "3-Year EPS Growth Rate": 29,
          "ROE": 0,
          "Last Qtr Sales % Chg": 7,
          "Last Qtr EPS % Chg": 16,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 22,
          "Company": "Campbell Soup",
          "Ticker": "CPB",
          "Industry": "Food-Packaged",
          "ESG Rating": "AA",
          "Composite Rating": 89,
          "Relative Strength": 91,
          "EPS Rating": 55,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": -10,
          "ROE": 56,
          "Last Qtr Sales % Chg": 2,
          "Last Qtr EPS % Chg": 14,
          "Dividend Yield": 3
        },
        {
          "Rank": 23,
          "Company": "CBRE Group",
          "Ticker": "CBRE",
          "Industry": "Real Estate Development/Operations",
          "ESG Rating": "AA",
          "Composite Rating": 89,
          "Relative Strength": 85,
          "EPS Rating": 94,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 19,
          "ROE": 24,
          "Last Qtr Sales % Chg": 12,
          "Last Qtr EPS % Chg": 9,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 24,
          "Company": "Quanta Services",
          "Ticker": "PWR",
          "Industry": "Building-Heavy Construction",
          "ESG Rating": "AA",
          "Composite Rating": 89,
          "Relative Strength": 82,
          "EPS Rating": 70,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 39,
          "ROE": 11,
          "Last Qtr Sales % Chg": 7,
          "Last Qtr EPS % Chg": -47,
          "Dividend Yield": 0.41
        },
        {
          "Rank": 25,
          "Company": "Eversource Energy",
          "Ticker": "ES",
          "Industry": "Utility-Electric Power",
          "ESG Rating": "AA",
          "Composite Rating": 88,
          "Relative Strength": 92,
          "EPS Rating": 68,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": 6,
          "ROE": 9,
          "Last Qtr Sales % Chg": 2,
          "Last Qtr EPS % Chg": -3,
          "Dividend Yield": 2.54
        },
        {
          "Rank": 26,
          "Company": "Procter & Gamble",
          "Ticker": "PG",
          "Industry": "Cosmetics/Personal Care",
          "ESG Rating": "AA",
          "Composite Rating": 88,
          "Relative Strength": 89,
          "EPS Rating": 75,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 7,
          "ROE": 23,
          "Last Qtr Sales % Chg": 4,
          "Last Qtr EPS % Chg": 17,
          "Dividend Yield": 2.54
        },
        {
          "Rank": 27,
          "Company": "ResMed",
          "Ticker": "RMD",
          "Industry": "Medical Products",
          "ESG Rating": "AA",
          "Composite Rating": 88,
          "Relative Strength": 89,
          "EPS Rating": 58,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 13,
          "ROE": 25,
          "Last Qtr Sales % Chg": 13,
          "Last Qtr EPS % Chg": 0,
          "Dividend Yield": 1.2
        },
        {
          "Rank": 28,
          "Company": "Agilent Technologies",
          "Ticker": "A",
          "Industry": "Medical-Research Equipment/Services",
          "ESG Rating": "AAA",
          "Composite Rating": 88,
          "Relative Strength": 76,
          "EPS Rating": 87,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 17,
          "ROE": 19,
          "Last Qtr Sales % Chg": 6,
          "Last Qtr EPS % Chg": 13,
          "Dividend Yield": 0.86
        },
        {
          "Rank": 29,
          "Company": "Axalta Coating Systems",
          "Ticker": "AXTA",
          "Industry": "Chemicals-Paints",
          "ESG Rating": "AA",
          "Composite Rating": 88,
          "Relative Strength": 71,
          "EPS Rating": 81,
          "SMR Rating": "C",
          "3-Year EPS Growth Rate": 15,
          "ROE": 29,
          "Last Qtr Sales % Chg": -5,
          "Last Qtr EPS % Chg": 13,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 30,
          "Company": "Alphabet",
          "Ticker": "GOOGL",
          "Industry": "Internet Content",
          "ESG Rating": "AA",
          "Composite Rating": 86,
          "Relative Strength": 81,
          "EPS Rating": 84,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 25,
          "ROE": 19,
          "Last Qtr Sales % Chg": 19,
          "Last Qtr EPS % Chg": -1,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 31,
          "Company": "McCormick & Co.",
          "Ticker": "MKC",
          "Industry": "Food-Misc. Preparation",
          "ESG Rating": "AA",
          "Composite Rating": 86,
          "Relative Strength": 78,
          "EPS Rating": 86,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 15,
          "ROE": 23,
          "Last Qtr Sales % Chg": 1,
          "Last Qtr EPS % Chg": 14,
          "Dividend Yield": 1.42
        },
        {
          "Rank": 32,
          "Company": "Vertex Pharmaceuticals",
          "Ticker": "VRTX",
          "Industry": "Medical-Biomed/Biotech",
          "ESG Rating": "AA",
          "Composite Rating": 86,
          "Relative Strength": 40,
          "EPS Rating": 99,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 120,
          "ROE": 32,
          "Last Qtr Sales % Chg": 25,
          "Last Qtr EPS % Chg": 34,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 33,
          "Company": "Tandem Diabetes Care",
          "Ticker": "TNDM",
          "Industry": "Medical Products",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 92,
          "EPS Rating": 61,
          "SMR Rating": "D",
          "3-Year EPS Growth Rate": "NA",
          "ROE": -240,
          "Last Qtr Sales % Chg": 173,
          "Last Qtr EPS % Chg": "NA",
          "Dividend Yield": "NA"
        },
        {
          "Rank": 34,
          "Company": "Kansas City Southern",
          "Ticker": "KSU",
          "Industry": "Transportation-Rail",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 90,
          "EPS Rating": 77,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 13,
          "ROE": 13,
          "Last Qtr Sales % Chg": 5,
          "Last Qtr EPS % Chg": 6,
          "Dividend Yield": 1.07
        },
        {
          "Rank": 35,
          "Company": "Sempra Energy",
          "Ticker": "SRE",
          "Industry": "Utility-Diversified",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 89,
          "EPS Rating": 65,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 6,
          "ROE": 10,
          "Last Qtr Sales % Chg": 3,
          "Last Qtr EPS % Chg": -19,
          "Dividend Yield": 2.67
        },
        {
          "Rank": 36,
          "Company": "General Mills",
          "Ticker": "GIS",
          "Industry": "Food-Packaged",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 85,
          "EPS Rating": 69,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 4,
          "ROE": 29,
          "Last Qtr Sales % Chg": -2,
          "Last Qtr EPS % Chg": 11,
          "Dividend Yield": 3.66
        },
        {
          "Rank": 37,
          "Company": "Amgen",
          "Ticker": "AMGN",
          "Industry": "Medical-Biomed/Biotech",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 80,
          "EPS Rating": 77,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 10,
          "ROE": 50,
          "Last Qtr Sales % Chg": -3,
          "Last Qtr EPS % Chg": 4,
          "Dividend Yield": 2.83
        },
        {
          "Rank": 38,
          "Company": "TriNet Group",
          "Ticker": "TNET",
          "Industry": "Commercial Services-Outsourcing",
          "ESG Rating": "AA",
          "Composite Rating": 85,
          "Relative Strength": 74,
          "EPS Rating": 84,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 50,
          "ROE": 75,
          "Last Qtr Sales % Chg": 10,
          "Last Qtr EPS % Chg": -20,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 39,
          "Company": "W.W. Grainger",
          "Ticker": "GWW",
          "Industry": "Retail/Wholesale Building Products",
          "ESG Rating": "AA",
          "Composite Rating": 84,
          "Relative Strength": 80,
          "EPS Rating": 65,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 18,
          "ROE": 52,
          "Last Qtr Sales % Chg": 1,
          "Last Qtr EPS % Chg": 6,
          "Dividend Yield": 1.87
        },
        {
          "Rank": 40,
          "Company": "T. Rowe Price Group",
          "Ticker": "TROW",
          "Industry": "Finance-Investment Management",
          "ESG Rating": "AA",
          "Composite Rating": 84,
          "Relative Strength": 78,
          "EPS Rating": 79,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 24,
          "ROE": 30,
          "Last Qtr Sales % Chg": 4,
          "Last Qtr EPS % Chg": 9,
          "Dividend Yield": 2.73
        },
        {
          "Rank": 41,
          "Company": "Adobe",
          "Ticker": "ADBE",
          "Industry": "Computer Software-Desktop",
          "ESG Rating": "AA",
          "Composite Rating": 84,
          "Relative Strength": 54,
          "EPS Rating": 97,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 43,
          "ROE": 37,
          "Last Qtr Sales % Chg": 24,
          "Last Qtr EPS % Chg": 18,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 42,
          "Company": "BWX Technologies",
          "Ticker": "BWXT",
          "Industry": "Electrical Power/Equipment",
          "ESG Rating": "AA",
          "Composite Rating": 83,
          "Relative Strength": 84,
          "EPS Rating": 66,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 12,
          "ROE": 91,
          "Last Qtr Sales % Chg": 7,
          "Last Qtr EPS % Chg": 7,
          "Dividend Yield": 1.2
        },
        {
          "Rank": 43,
          "Company": "Marsh & McLennan",
          "Ticker": "MMC",
          "Industry": "Insurance Brokers",
          "ESG Rating": "AA",
          "Composite Rating": 82,
          "Relative Strength": 75,
          "EPS Rating": 84,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 14,
          "ROE": 29,
          "Last Qtr Sales % Chg": 16,
          "Last Qtr EPS % Chg": 7,
          "Dividend Yield": 1.86
        },
        {
          "Rank": 44,
          "Company": "Healthpeak Properties",
          "Ticker": "PEAK",
          "Industry": "Finance-Property REIT",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 93,
          "EPS Rating": 26,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": "NA",
          "ROE": 18,
          "Last Qtr Sales % Chg": 5,
          "Last Qtr EPS % Chg": "NA",
          "Dividend Yield": 4.03
        },
        {
          "Rank": 45,
          "Company": "Aecom",
          "Ticker": "ACM",
          "Industry": "Building-Heavy Construction",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 92,
          "EPS Rating": 66,
          "SMR Rating": "D",
          "3-Year EPS Growth Rate": -5,
          "ROE": 10,
          "Last Qtr Sales % Chg": -3,
          "Last Qtr EPS % Chg": 16,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 46,
          "Company": "PepsiCo",
          "Ticker": "PEP",
          "Industry": "Food-Packaged",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 87,
          "EPS Rating": 55,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 6,
          "ROE": 63,
          "Last Qtr Sales % Chg": 4,
          "Last Qtr EPS % Chg": -2,
          "Dividend Yield": 2.8
        },
        {
          "Rank": 47,
          "Company": "Intuit",
          "Ticker": "INTU",
          "Industry": "Computer Software-Financial",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 85,
          "EPS Rating": 60,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 24,
          "ROE": 54,
          "Last Qtr Sales % Chg": 15,
          "Last Qtr EPS % Chg": "NA",
          "Dividend Yield": 0.78
        },
        {
          "Rank": 48,
          "Company": "Cummins",
          "Ticker": "CMI",
          "Industry": "Trucks & Parts-Heavy Duty",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 72,
          "EPS Rating": 93,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 25,
          "ROE": 29,
          "Last Qtr Sales % Chg": 1,
          "Last Qtr EPS % Chg": 30,
          "Dividend Yield": 3.15
        },
        {
          "Rank": 49,
          "Company": "Waters Corp.",
          "Ticker": "WAT",
          "Industry": "Medical Systems/Equipment",
          "ESG Rating": "AA",
          "Composite Rating": 81,
          "Relative Strength": 59,
          "EPS Rating": 79,
          "SMR Rating": "A",
          "3-Year EPS Growth Rate": 11,
          "ROE": 33,
          "Last Qtr Sales % Chg": 0,
          "Last Qtr EPS % Chg": 10,
          "Dividend Yield": "NA"
        },
        {
          "Rank": 50,
          "Company": "Methode Electronics",
          "Ticker": "MEI",
          "Industry": "Electronics-Parts",
          "ESG Rating": "AA",
          "Composite Rating": 79,
          "Relative Strength": 90,
          "EPS Rating": 53,
          "SMR Rating": "B",
          "3-Year EPS Growth Rate": 14,
          "ROE": 16,
          "Last Qtr Sales % Chg": 21,
          "Last Qtr EPS % Chg": 14,
          "Dividend Yield": 1.31
        }
      ]
}

